name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.6'
      - run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: install pycodestyle
        run: pip install pycodestyle

      - name: pycodestyle check
        run: pycodestyle ./
