name: CI

on:
  push:
    branches:
      - '*'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8.10'
      - run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: install pycodestyle
        run: pip install pycodestyle

      - name: pycodestyle check
        run: pycodestyle ./
